// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package data

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed bin/launcher_background.png
var ResourceLauncherbackgroundPngData []byte
var ResourceLauncherbackgroundPng = &fyne.StaticResource{
	StaticName:    "launcher_background.png",
	StaticContent: ResourceLauncherbackgroundPngData,
}
