// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package data

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed bin/launcher_background_blurred.png
var ResourceLauncherbackgroundblurredPngData []byte
var ResourceLauncherbackgroundblurredPng = &fyne.StaticResource{
	StaticName:    "launcher_background_blurred.png",
	StaticContent: ResourceLauncherbackgroundblurredPngData,
}
