// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed launcher_background_blurred.png
var resourceLauncherbackgroundblurredPngData []byte
var resourceLauncherbackgroundblurredPng = &fyne.StaticResource{
	StaticName:    "launcher_background_blurred.png",
	StaticContent: resourceLauncherbackgroundblurredPngData,
}
