// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed launcher_background.png
var resourceLauncherbackgroundPngData []byte
var resourceLauncherbackgroundPng = &fyne.StaticResource{
	StaticName:    "launcher_background.png",
	StaticContent: resourceLauncherbackgroundPngData,
}
